### ISSUE TITLE
[FEEDBACK] This is a test to see if I can get Github to work

### ISSUE THREAD

**Issue by CMAutoIssue** [DungeoneerExalt/ZeroRaidBot#46]
### Version
0.6.0-pre.1

### Feedback
Testing to see if Github accepts this

### Submitter Information
Discord Tag: Developer Testing
Discord ID: Developer Testing
Date/Time Submitted: 7/19/2020, 1:26:57 PM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
ez
