### ISSUE TITLE
[BUG REPORT] Darkmattr sucks

### ISSUE THREAD

**Issue by CMAutoIssue** [DungeoneerExalt/ZeroRaidBot#47]
### Version
0.6.0-pre.1

### Description
darkmattr sucks. what else?

### Location of Error
Darkmattr's github

### Reproduction Steps
1. test
2. test
3. github test

### Relevant Error Message
None

### Other Information
none

### Submitter Information
Discord Tag: Developer Testing
Discord ID: Developer Testing
Date/Time Submitted: 7/19/2020, 1:57:19 PM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
cool. test successful, pushing commit
