### ISSUE TITLE
[FEEDBACK] A command that allows helpers to manually verify someone in case the bot is down

### ISSUE THREAD

**Issue by CMAutoIssue** [DungeoneerExalt/ZeroRaidBot#54]
### Version
0.1.0

### Feedback
A command that allows users of the helper role and above to manual verify members in the chance the bot is currently down, as currently we cannot do this yet part of what we're meant to do is make sure the verification process goes smoothly

### Submitter Information
Discord Tag: Shel#7239
Discord ID: 285042785747337216
Date/Time Submitted: 7/21/2020, 1:04:03 PM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
not possible at this time because, well, if a bot is down, you can't really manually verify with the said bot
