### ISSUE TITLE
[BUG REPORT] ....

### ISSUE THREAD

**Issue by CMAutoIssue** [DungeoneerExalt/ZeroRaidBot#56]
### Version
0.6.0-pre.4

### Description
....

### Reproduction Steps
....

### Other Information
nahh

### Submitter Information
Discord Tag: Darkmatter#7321
Discord ID: 196282885601361920
Date/Time Submitted: 7/21/2020, 2:08:15 PM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
thanks for the test
