### ISSUE TITLE
[FEEDBACK] Control Panel VC Notification

### ISSUE THREAD

**Issue by CMAutoIssue** [DungeoneerExalt/ZeroRaidBot#59]
### Version
0.6.0-pre.5

### Feedback
Put the part that talks about how you must be in VC in order to use control panel command as the string content, not part of embed

### Submitter Information
Discord Tag: Developer
Discord ID: Developer
Date/Time Submitted: 7/23/2020, 12:28:56 AM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
done
