### ISSUE TITLE
[BUG REPORT] The general idea is a bug i encountered while trying to suggest a feature

### ISSUE THREAD

**Issue by CMAutoIssue** [DungeoneerExalt/ZeroRaidBot#61]
### Version
0.6.0-pre.5

### Description
Sometimes when you use the suggest feature and the bot dms you, the lightbulb will not appear, not allowing you to suggest a feature

### Reproduction Steps
I came across this bug by using the command in the staff commands channel, simple as that

### Other Information
I've only encountered this bug once so far, I'll likely see if it appears again

### Submitter Information
Discord Tag: Shel#7239
Discord ID: 285042785747337216
Date/Time Submitted: 7/24/2020, 9:55:37 AM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
Sometimes, the bot decides it doesn't want to react. I'm still looking into it.
