### ISSUE TITLE
[BUG REPORT] vet raiders can see the vet bot commands

### ISSUE THREAD

**Issue by CMAutoIssue** [DungeoneerExalt/ZeroRaidBot#63]
### Version
0.6.0-pre.7

### Description
errors with the channel perms allow us to see the channel (ex: https://imgur.com/eIhFfQJ)

### Reproduction Steps
someone messed up the perms and allowed vet raiders to see the channel, it probably has something to do with syncing the channel perms with the category perms that allows us to see it

### Other Information
no other details

### Submitter Information
Discord Tag: skyrimnerd172#6356
Discord ID: 118534330166411270
Date/Time Submitted: 7/25/2020, 1:17:26 AM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
This is unfortunately not a bot bug. Sorry.
