### ISSUE TITLE
[BUG REPORT] Fix control panel reaction handling

### ISSUE THREAD

**Issue by CMAutoIssue** [DungeoneerExalt/ZeroRaidBot#64]
### Version
0.6.0-pre.7

### Description
Zero removes any reaction by a user on any message in the control panel channel.
Fix:
add a check to only remove reactions on messages that zero itself sends

### Reproduction Steps
none

### Other Information
always occurs

### Submitter Information
Discord Tag: Darkmatter#7321
Discord ID: 196282885601361920
Date/Time Submitted: 7/25/2020, 6:47:35 AM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
To be acknowledged by tomorrow.
