### ISSUE TITLE
[FEEDBACK] Give officer no runs command access

### ISSUE THREAD

**Issue by CMAutoIssue** [DungeoneerExalt/ZeroRaidBot#75]
### Version
0.6.2-pre.5

### Feedback
Title

### Submitter Information
Discord Tag: Karma's Guide#6864
Discord ID: 165929337869041665
Date/Time Submitted: 8/26/2020, 9:42:12 PM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
Fixing this right now.
