### ISSUE TITLE
[FEEDBACK] Make mod mail threads close after 24 hours of inactivity

### ISSUE THREAD

**Issue by CMAutoIssue** [DungeoneerExalt/ZeroRaidBot#77]
### Version
0.6.2-pre.5

### Feedback
Make mod mail threads close after 24 hours of inactivity

### Submitter Information
Discord Tag: Karma's Guide#6864
Discord ID: 165929337869041665
Date/Time Submitted: 8/27/2020, 9:30:06 AM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
This will be considered.
