### ISSUE TITLE
[BUG REPORT] Raiders aren't getting logged keys. Handaewi getting database error and he verified correctly. He is in VC and bot did not dm him when key.

### ISSUE THREAD

**Issue by CMAutoIssue** [DungeoneerExalt/ZeroRaidBot#79]
### Version
0.6.2-pre.5

### Description
Happens in Event-Bot-Commands and Stergar can log keys for himself but cannot for Handaeri same for Handaewi.

### Reproduction Steps
Tried to log keys

### Other Information
nope

### Submitter Information
Discord Tag: BluBlazing#0151
Discord ID: 209906645742911488
Date/Time Submitted: 9/11/2020, 9:34:26 PM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
will look into.

**Comment by ewang2002** [comment]
Resolved. The person needs to verify with the bot (i.e. the bot needs to give the Verified role)
